---
title: "Caret - Tutorial"
author: "Nils sandøy"
date: "October 14, 2015"
output: pdf_document
---

```{r}
library(caret)
data(segmentationData) 
# get rid of the cell identifier 
segmentationData$Cell <- NULL

training <- subset(segmentationData, Case == "Train")
testing <- subset(segmentationData, Case == "Test") 
training$Case <- NULL 
testing$Case <- NULL 
str(training[,1:6])

```

# Centering and scaling

## Estimate the standardization parameters (preProcess)
```{r}
trainX <- training[, names(training) != "Class"]
## Methods are "BoxCox", "YeoJohnson", center", "scale",
## "range", "knnImpute", "bagImpute", "pca", "ica" and
## "spatialSign"
preProcValues <- preProcess(trainX, method = c("center", "scale"))
preProcValues
```

## Apply the standardization parameters to the data sets
```{r}
scaledTrain <- predict(preProcValues, trainX)
str(scaledTrain)
```

## To obtain a shallow tree with rpart:
```{r}
library(rpart)
rpart1 <- rpart(Class ~ ., data = training, control = rpart.control(maxdepth = 2))
rpart1
```
